### ISSUE TITLE
imagefanreloaded 1.2024.06.01 shaking when new folder opened

### ISSUE THREAD

**Issue by scomnoob** [mihnea-radulescu/imagefanreloaded#5]
left part is changing its size https://youtu.be/fEL6nXjdz5k

its very annoying

also it will be KILLER FEATURE - to show subfolder images - no image app can do it right now in 2024......

**Comment by mihnea-radulescu** [comment]
Hi @scomnoob,

I'm sorry, but I cannot access the provided link, since it seems to have been deleted by YouTube.

As far as I can understand the issue, the folder tree view needs to expand horizontally, especially if the accessed folder is deeply nested in the folder structure. The folder tree view has a horizontal scroll bar, and can be resized, using the vertical slider between the folders and the thumbnails view.

Regarding the issue of recursively "flattening" a folder with its sub-folders into a joint thumbnails view, there are some significant drawbacks involved, which is why, I assume, other image viewers have not implemented it either:
- **system resources**, since a folder could recursively contain tens of thousands of sub-folders, with potentially millions of images, for which the thumbnail generation would require more system memory than the system can provide. E.g. a folder structure containing 100 GB of images in a system featuring 16 GB or RAM.
- **meaningful ordering of images** in the thumbnails view, should it be name-based (what about image files having the same name?), should the thumbnails sequence be rendered by navigating the folder tree structure in order (which order, breadth-first or depth-first?)

I suppose that this joint folder with sub-folders view mode could be implemented in a limited sense, by manually selecting a folder of manageable size, and having it be rendered recursively in the thumbnails view, based on some kind of ordering of the nested image files. I don't know, however, if and when I will implement this feature, since it quite niche, and tricky to get right.

If you have reproducible info on the folder tree view resizing, I can look specifically into that issue.

**Comment by scomnoob** [comment]
New link with that behavior

https://youtu.be/S4ycDpndp-w

About images in subfolders - you are right... ram usage...tralala... for example - i have about 2k folders with with less then 1k photo in each with deep folder structure

I know - if i will see subfolder photos when using them - it will be like are MIRACLE...but,,,for example - xnview mp  - i should click smth like 'view included photos'  on EACH folder i need... other software - almost the same...brrr..

Well looks like i will write my one on c#...

**Comment by mihnea-radulescu** [comment]
Thank you, @scomnoob, for providing a new link, but private YouTube videos cannot be opened by anyone other than their owner.

If a video cannot be linked, then you can describe the issue in a text-only format.

Having thought a bit more about the recursive thumbnail generation feature, I will implement it by the end of the month of June, perhaps sooner.

**Comment by scomnoob** [comment]
Oh sorry, changed video permission - access by url

**Comment by mihnea-radulescu** [comment]
Hi @scomnoob,

Adding the recursive folder image browsing feature has proven itself to be much simpler than anticipated.

Pressing the key R while browsing a folder toggles the recursive view on and off.

I have prepared a preliminary release for you to check how this feature works here: https://github.com/mihnea-radulescu/imagefanreloaded/releases/tag/1.2024.06.14.

Please let me know if the feature behaves as expected.

**Comment by scomnoob** [comment]
> Hi @scomnoob,
> 
> Adding the recursive folder image browsing feature has proven itself to be much simpler than anticipated.
> 
> Pressing the key R while browsing a folder toggles the recursive view on and off.
> 
> I have prepared a preliminary release for you to check how this feature works here: https://github.com/mihnea-radulescu/imagefanreloaded/releases/tag/1.2024.06.14.
> 
> Please let me know if the feature behaves as expected.

it works
it will be great if press R - will turn on that mode for all folders...now i need to press it every time on each folders

MANY THANKS!

**Comment by mihnea-radulescu** [comment]
Hi @scomnoob,

Regarding a persistent recursive mode that does not reset after changing the folder, I am wary of this, since the user could very likely forget about the setting, and then be astonished why some other (large) folder takes significant time to load and consumes considerable system resources.

However, if you want to change this setting for your own personal use, you can simply remove (or comment out) the line no. 241 __recursiveFolderAccess = false;_ within the method _private void OnFolderTreeViewSelectedItemChanged(object? sender, SelectionChangedEventArgs e)_ in the code file _ImageFanReloaded/ImageFanReloaded/Controls/ContentTabItem.axaml.cs_, and then recompile the application.

Regarding the "shaking bug", this is related to the underlying UI framework **Avalonia UI**, and the same (or similar) bug has already been raised on their GitHub: https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid/issues/298.
