### ISSUE TITLE
image resize for previews

### ISSUE THREAD

**Issue by scomnoob** [mihnea-radulescu/imagefanreloaded#7]
Hello
Many thanks for your app
Its first time i can work with my 400k images with multiple sub folders without butthurt !

(lol youtube deleted my channel because of videos sent to you to debug - lol - but fuck them i dont care...)

can you pls add ability to resize image preview in gui ?

smth like 

![image](https://github.com/mihnea-radulescu/imagefanreloaded/assets/13706354/5dd6465a-3ea6-4ef2-890f-db1c2df1a22f)

MANY THANKS DUDE!!!!!

Now with that subfolders feature your app is really unic. You should describe that shift R somewhere :)

**Comment by mihnea-radulescu** [comment]
Hi @scomnoob,

Thank you for proposing this change!

I have implemented configurable thumbnail sizes, ranging from **50** to **500** pixels, accessible through the property **ThumbnailSizeInPixels** in the newly-added file **AppSettings.json**. The property must be updated before the application is started, in order to have an effect.

Link to the release: [https://github.com/mihnea-radulescu/imagefanreloaded/releases/tag/1.2024.07.11](https://github.com/mihnea-radulescu/imagefanreloaded/releases/tag/1.2024.07.11)

**Comment by scomnoob** [comment]
it works thx!
no chance to edit it from gui?

**Comment by mihnea-radulescu** [comment]
Hi @scomnoob,

I plan to add a menu system to the UI that would include a Settings menu. I cannot offer a timeline for this, though.

**Comment by scomnoob** [comment]
many thanks for app
only butthurt i have - cant use up/down in treeview... ()))
